"""
backend/ai/providers/base.py

Abstract base class, typed exceptions, and shared data structures for AI provider integrations.
All providers (Gemini, Groq) implement this adapter-based interface.
"""
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union


# ── Exceptions ────────────────────────────────────────────────────────────────

class AIException(Exception):
    """Base exception for all Syllabot AI module errors."""
    pass


class ProviderError(AIException):
    """General error returned by a specific LLM provider API."""
    pass


class RetryableError(ProviderError):
    """Transient errors that are safe to retry with backoff (e.g. HTTP 503, connection timeouts)."""
    pass


class QuotaExceededError(ProviderError):
    """Errors caused by exceeding plan limits or total quota caps (e.g. daily quota reached)."""
    pass


class RateLimitError(ProviderError):
    """Errors caused by short-term rate limits (e.g. requests per minute)."""
    pass


class AuthenticationError(ProviderError):
    """Invalid API key or authentication failures on the provider side."""
    pass


class ValidationError(ProviderError):
    """Bad request payloads, model validation failures, or invalid schema parameters."""
    pass


class ProviderUnavailableError(ProviderError):
    """API key is missing or the provider has been explicitly disabled in settings."""
    pass


class SerializationError(AIException):
    """Failed to convert messages or tool schemas between unified and provider-native structures."""
    pass


class AllProvidersUnavailableError(AIException):
    """Raised by ModelRouter when no configured providers are healthy/available."""
    def __init__(self, reason: str = ""):
        message = "No AI provider is currently available."
        if reason:
            message += f" Details: {reason}"
        super().__init__(message)


# ── Shared Data Types ─────────────────────────────────────────────────────────

@dataclass
class ToolCall:
    """Represents a single tool call request generated by the LLM."""
    id: str
    name: str
    arguments: Dict[str, Any]


@dataclass
class Message:
    """
    Unified conversation message representation.
    
    Attributes:
        role:          The sender role ("system", "user", "assistant", "tool").
        content:       The text payload of the message.
        tool_calls:    List of tool calls requested (for assistant messages).
        tool_call_id:  ID matching the assistant's tool call (for tool messages).
    """
    role: str
    content: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None


@dataclass
class ProviderResponse:
    """
    Unified response payload returned by all provider adapters.
    """
    content: Optional[str]
    tool_calls: List[ToolCall] = field(default_factory=list)
    provider: str = ""
    model: str = ""
    latency_ms: float = 0.0


# ── Abstract Provider Adapter ─────────────────────────────────────────────────

class AIProvider(ABC):
    """
    Abstract Base Class for AI Provider Adapters.
    Uses the Template Method pattern to standardize request execution,
    exception mapping, telemetry collection, and formatting.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable provider key (e.g. 'gemini', 'groq')."""
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """Lightweight check to see if the provider is configured (API key set)."""
        pass

    @abstractmethod
    def _require_available(self) -> None:
        """Raises ProviderUnavailableError if API key is missing."""
        pass

    # ── Adapter Contract Methods ──────────────────────────────────────────────

    @abstractmethod
    def prepare_messages(self, messages: List[Message], system_prompt: Optional[str]) -> Any:
        """Convert normalized Message objects into provider-native format."""
        pass

    @abstractmethod
    async def execute(
        self,
        payload: Any,
        tools: Optional[List[Dict[str, Any]]] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> Any:
        """Invoke the provider SDK or HTTP client with parsed arguments."""
        pass

    @abstractmethod
    def parse_response(self, raw_response: Any) -> ProviderResponse:
        """Translate provider-native response format to unified ProviderResponse."""
        pass

    @abstractmethod
    def handle_errors(self, exception: Exception) -> Exception:
        """Inspect provider exception details and wrap them in a typed exception."""
        pass

    # ── Capabilities ──────────────────────────────────────────────────────────

    @abstractmethod
    def supports_tools(self) -> bool:
        """True if the adapter supports function/tool calling."""
        pass

    @abstractmethod
    def supports_images(self) -> bool:
        """True if the adapter supports multimodal image attachments."""
        pass

    @abstractmethod
    def supports_streaming(self) -> bool:
        """True if the adapter supports chunked token streaming."""
        pass

    # ── Template Methods ──────────────────────────────────────────────────────

    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> ProviderResponse:
        """Wrapper for single-turn text completions."""
        messages = [Message(role="user", content=prompt)]
        return await self.generate_with_messages(
            messages=messages,
            system_prompt=system_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
        )

    async def generate_with_tools(
        self,
        messages: Union[List[Dict[str, Any]], List[Message]],
        tools: List[Dict[str, Any]],
        system_prompt: Optional[str] = None,
        temperature: float = 0.1,
    ) -> ProviderResponse:
        """Wrapper for tool calling operations."""
        # Convert list of raw dicts if passed from legacy agent / graph nodes
        normalized_messages = []
        for msg in messages:
            if isinstance(msg, Message):
                normalized_messages.append(msg)
            elif isinstance(msg, dict):
                # Map raw dict properties
                t_calls = None
                if "tool_calls" in msg and msg["tool_calls"]:
                    t_calls = [
                        ToolCall(id=tc["id"], name=tc["name"], arguments=tc.get("arguments", {}))
                        for tc in msg["tool_calls"]
                    ]
                normalized_messages.append(Message(
                    role=msg.get("role", "user"),
                    content=msg.get("content"),
                    tool_calls=t_calls,
                    tool_call_id=msg.get("tool_call_id")
                ))
            else:
                raise SerializationError("Invalid message format: must be Message dataclass or dict.")

        return await self.generate_with_messages(
            messages=normalized_messages,
            system_prompt=system_prompt,
            tools=tools,
            temperature=temperature,
            max_tokens=2048,
        )

    async def generate_with_messages(
        self,
        messages: List[Message],
        system_prompt: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> ProviderResponse:
        """
        Runs the full adapter execution pipeline.
        Manages logging, error handling, and latency tracking.
        """
        self._require_available()
        start_time = time.perf_counter()

        try:
            payload = self.prepare_messages(messages, system_prompt)
            raw_response = await self.execute(payload, tools, temperature, max_tokens)
            response = self.parse_response(raw_response)
            
            latency = (time.perf_counter() - start_time) * 1000
            response.latency_ms = latency
            response.provider = self.name
            return response

        except Exception as e:
            classified = self.handle_errors(e)
            raise classified
